version: "3"
services:
  db:
    env_file:
      - .env.development.local
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  web:
    build: .
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./api:/app/api
    ports:
      - 8000:8000
    env_file:
      - .env.development.local
    depends_on:
      - db

volumes:
  postgres_data:
